name = "create-server-pack"
author = "KatKak"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96f32e60badc6702bf8261e37698c2bd979c3a8b4ecc659c287fce97fc86567b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
