name = "create-server-pack"
author = "KatKak"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4de264d3e7a4dc6dc31fa5acd08688aec97587b99873fbb4d6f87e65607bc6b1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
