name = "create-server-pack"
author = "KatKak"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf990b7d2e8c35215bb6f826437f06eed769ab562406e48874f696ca26fa8bc"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
